### ISSUE TITLE
Unable to replicate theme option

### ISSUE THREAD

**Issue by AlexGoico** [adamsiwiec/hexagon#3]
After downloading hexo-cli I downloaded hexagon then hexo-server, and hexo-admin globally. I then run
```javascript
hexo init blog-test
cd blog-test/
hexagon theme ppoffice/hexo-theme-hueman
```
but get the following traceback
```

⬡

Error: spawn git ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by adamsiwiec** [comment]
Thanks @typedeph for the issue, I will do some quick debugging then get back to you.

**Comment by adamsiwiec** [comment]
I think the problem is that you do not have git installed,  because it fails when trying to start a git process. Try checking out [Git's download website](https://git-scm.com/downloads) to install. Comment if this still doesn't work or you need more guidance.
