### ISSUE TITLE
can't install any plugin

### ISSUE THREAD

**Issue by noxsave** [adamsiwiec/hexagon#8]
win10 x64+nodejs+git+hexo+hexagon
---
everything is good and I can use hexagon to install a theme

but I can't use hexagon to install any plugin

for example:
> hexagon -p hexo-hey
> 
> × Installing packages
> ⚠️ Uh Oh! Something went wrong check npm-debug.log for more info

**Comment by adamsiwiec** [comment]
Can I get some more information about your system (node version, npm version) also can you include that npm-debug.log. I think this error is in your environment and not with Hexagon, as I can't duplicate. Cheers!

**Comment by noxsave** [comment]
@adamsiwiec thanks for your help ：）
this is more info:

version info:
```
PS D:\> hexo -v
hexo-cli: 1.0.4
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

PS D:\> npm -v
5.6.0
```

debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\App\\nodejs\\node.exe',
1 verbose cli   'D:\\App\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '--save',
1 verbose cli   'h',
1 verbose cli   'e',
1 verbose cli   'x',
1 verbose cli   'o',
1 verbose cli   '-',
1 verbose cli   'h',
1 verbose cli   'e',
1 verbose cli   'y' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session aded3bce78f08c27
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/o 595ms (from cache)
8 http fetch GET 304 https://registry.npmjs.org/e 598ms (from cache)
9 http fetch GET 304 https://registry.npmjs.org/h 605ms (from cache)
10 silly pacote tag manifest for o@latest fetched in 599ms
11 silly pacote tag manifest for e@latest fetched in 601ms
12 http fetch GET 304 https://registry.npmjs.org/x 600ms (from cache)
13 silly pacote tag manifest for h@latest fetched in 637ms
14 silly pacote tag manifest for x@latest fetched in 601ms
15 http fetch GET 304 https://registry.npmjs.org/y 1597ms (from cache)
16 silly pacote tag manifest for y@latest fetched in 1598ms
17 http fetch GET 404 https://registry.npmjs.org/- 2057ms
18 silly fetchPackageMetaData error for -@latest 404 Not Found: -@latest
19 verbose stack Error: 404 Not Found: -@latest
19 verbose stack     at fetch.then.res (D:\App\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
19 verbose stack     at tryCatcher (D:\App\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
19 verbose stack     at Promise._settlePromiseFromHandler (D:\App\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
19 verbose stack     at Promise._settlePromise (D:\App\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
19 verbose stack     at Promise._settlePromise0 (D:\App\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
19 verbose stack     at Promise._settlePromises (D:\App\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
19 verbose stack     at Async._drainQueue (D:\App\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
19 verbose stack     at Async._drainQueues (D:\App\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
19 verbose stack     at Immediate.Async.drainQueues (D:\App\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
19 verbose stack     at runCallback (timers.js:789:20)
19 verbose stack     at tryOnImmediate (timers.js:751:5)
19 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
20 verbose cwd D:\onedrive\eniche\hexo
21 verbose Windows_NT 10.0.16299
22 verbose argv "D:\\App\\nodejs\\node.exe" "D:\\App\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "h" "e" "x" "o" "-" "h" "e" "y"
23 verbose node v8.9.4
24 verbose npm  v5.6.0
25 error code E404
26 error 404 Not Found: -@latest
27 verbose exit [ 1, true ]
```

**Comment by adamsiwiec** [comment]
That’s a strange error log, I’ll poke around on my windows system, tomorrow.

**Comment by noxsave** [comment]
@adamsiwiec ok,thanks.if there is a new discovery about this error I'll tell you again.

**Comment by jerrywcy** [comment]
have you guys fixed this problem?I've got a same one.
